Aluno escolhe plano um plano
TreinaDev/enrollment-system pull request #2
Opened 2021-03-18 00:56 UTC by tiofih

Este pull request resolve o quadro [Aluno escolhe um plano](https://trello.com/c/UQttTPR6/21-aluno-escolhe-um-plano)

2021-03-18 15:29 UTC, HenriqueMorato commented on app/models/payment_method.rb
> +    return payment_methods
Acho que uma troca simples desse each pra um map pode evitar várias variáveis, porque aí o retorno já vai transformado, o que acha?

```suggestion
    json_response.map do |response|
      PaymentMethod.new(response) # se o json vem exatamente nesse formato talvez você consiga passar o hash direto
    end
```

2021-03-18 15:29 UTC, HenriqueMorato commented on app/models/payment_method.rb
> +  end
Esse método tá sendo usado?

2021-03-18 15:29 UTC, HenriqueMorato commented on spec/features/customer_choose_plan_spec.rb
> +    allow(PaymentMethod).to receive(:all).and_return(payment_methods)
Seria interessante usar factory_bot nos testes, fiz uma sugestão nesse mas tem outros abaixo que seria legal trocar, o que acham?

```suggestion
    yoga = create(:class_category, name: 'Yoga')
    first_plan = create(:plan, name: 'PlanoFit', montlhy_rate: 200, monthly_class_limit: 5)
    second_plan = create(:plan, name: 'PlanoSmart', montlhy_rate: 300, monthly_class_limit: 7)
    class_category_plan = create(:class_category_plan, plan: first_plan, class_category: yoga)
    ccred = PaymentMethod.new(name: 'Cartão de Crédito', code: 'CCRED')
    bol = PaymentMethod.new(name: 'Boleto', code: 'BOL')
    allow(PaymentMethod).to receive(:all).and_return([ccred, bol])
```

2021-03-18 15:29 UTC, HenriqueMorato commented on spec/models/class_category_plan_spec.rb
> +require 'rails_helper'
Esse arquivo como não está sendo usado o que acha de apagar?

2021-03-18 15:29 UTC, HenriqueMorato commented on spec/models/class_category_spec.rb
> -  pending "add some examples to (or delete) #{__FILE__}"
Esse arquivo como não está sendo usado o que acha de apagar?

2021-03-18 15:29 UTC, HenriqueMorato commented on spec/models/customer_spec.rb
> -RSpec.describe Customer, type: :model do
Esse arquivo como não está sendo usado o que acha de apagar?

2021-03-18 15:29 UTC, HenriqueMorato commented on spec/models/enrollment_spec.rb
> -  pending "add some examples to (or delete) #{__FILE__}"
Esse arquivo como não está sendo usado o que acha de apagar?

2021-03-18 15:29 UTC, HenriqueMorato commented on spec/models/plan_spec.rb
> -  pending "add some examples to (or delete) #{__FILE__}"
Esse arquivo como não está sendo usado o que acha de apagar?

2021-03-18 15:29 UTC, HenriqueMorato commented on spec/models/user_spec.rb
> -  pending "add some examples to (or delete) #{__FILE__}"
Esse arquivo como não está sendo usado o que acha de apagar?

2021-03-18 15:29 UTC, HenriqueMorato commented on app/models/payment_method.rb
> +    return [] if response.status == 403
Essa linha acho que está sem teste, podem conferir? Talvez nem faça tanto sentido validar o 403 ainda

2021-03-18 23:05 UTC, joaorsalmeida commented on app/models/payment_method.rb
> +    #return payment_methods
Que tal remover esse comentário?

2021-03-18 23:07 UTC, joaorsalmeida commented on app/views/home/index.html.erb
> +      <%= plan.name %>
Essa view, pensando no usuário final, ficou um pouco ruim de legibilidade. Depois do nome vão aparecer dois números sem muito contexto né?! Que tal indicar melhor do que se trata (mensalidade, limite de aulas no mês, aulas disponíveis etc...)

2021-03-18 23:07 UTC, joaorsalmeida commented on app/views/home/index.html.erb
> +    <% @payment_methods.each do |pm| %>
Mesmo ponto da legibilidade aqui ;)

2021-03-18 23:08 UTC, joaorsalmeida requested changes
Pessoal, pedi mais alguns ajustes

2021-03-19 19:58 UTC, joaorsalmeida approved these changes

2021-03-19 21:59 UTC, merged