Generate token
TreinaDev/enrollment-system pull request #4
Opened 2021-03-19 01:09 UTC by sancheslz

Este PR recebe os dados do cliente da API de aulas e gera um token único para validação nas demais dependências do sistema.

2021-03-19 19:27 UTC, joaorsalmeida requested changes
Pessoal, senti falta de um cenário de falha. O `customer` tem várias validações, mas o que acontece quando chega uma requisição incompleta via API?

2021-03-23 00:44 UTC, sancheslz commented
Este PR recebe os dados do cliente da API de aulas e gera um token único para validação nas demais dependências do sistema. Adicionado cenário de falha e consulta do token.

2021-03-23 01:30 UTC, sancheslz commented
Resolve conflitos: nova feature gerar token

2021-03-23 01:35 UTC, sancheslz commented
Resolve conflitos: nova feature gerar token

2021-03-23 16:18 UTC, joaorsalmeida approved these changes

2021-03-23 23:25 UTC, merged